---
title: "Bike Shares Daily"
author: "Lukman Aliyu"
format: dashboard
orientation: columns
vertical_layout: fill
storyboard: true
---






```{r setup, include=FALSE}
library(leaflet)
library(DT)
library(tidyverse)

trips_df <- read_csv('https://assets.datacamp.com/production/repositories/1448/datasets/1f12031000b09ad096880bceb61f6ca2fd95e2eb/sanfran_bikeshare_joined_oneday.csv')
```

### Most bikes are used only a few times, but a few are used a lot

```{r}

trips_per_bike_df <- trips_df %>%
  group_by(bike_number) %>%
  summarize(n_trips = n()) %>%
  arrange(desc(n_trips)) 

trips_per_bike_df %>%
  ggplot(aes(x = n_trips)) +
  geom_histogram(binwidth = 1) +
  ylab('') +
  xlab('Trips per bike') 

```

### Where did the most used bike go?

```{r}

most_used_bike_df <- trips_df %>%
  filter(bike_number == trips_per_bike_df$bike_number[1])

most_used_bike_df %>%
  rename(latitude = start_latitude,
         longitude = start_longitude) %>%
  group_by(start_station_id, latitude, longitude) %>%
  count() %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers()

```
***

* Bike `r most_used_bike_df$bike_number[1]` made its first trip from `r most_used_bike_df$start_station_name[1]` and ended its day at `r most_used_bike_df$end_station_name[nrow(most_used_bike_df)]`.
* Its longest trip was `r max(most_used_bike_df$duration_sec)/60` minutes long.


